apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: rieicp/simple-app
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    path: helm/simple-spring-app-4-testing-debugging-in-k8s
    repoURL: https://github.com/rieicp/simple-java-app.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
